name: dotnet Package

#on:
#  release:
#    types: [created]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish-gpr:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          registry-url: https://nuget.pkg.github.com/escalonc/index.json
        env:
          PACKAGES_GITHUB_TOKEN: ${{secrets.PACKAGES_GITHUB_TOKEN}}
      - run: ls ./src/NoSqlRepositories
#      - run: dotnet nuget push "./src/NoSqlRepositories/bin/Debug/NoSqlRepositories.1.0.0.nupkg" --api-key ${{secrets.PACKAGES_GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/escalonc/index.json"